<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.0.1</Version>
    <Authors>Rylan Barnes</Authors>
    <Company>Web4 Foundation</Company>
    <Product>Keyholes</Product>
    <Description>Keyholes - a common abstraction for bridging into the DOM from WebAssembly or WebSockets</Description>
    <Copyright>Copyright © Rylan Barnes 2026</Copyright>
    <Summary>Keyholes - a common abstraction for bridging into the DOM from WebAssembly or WebSockets</Summary>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Title>Keyholes</Title>
    <PackageId>Keyholes</PackageId>
    <PackageVersion>0.0.1</PackageVersion>
    <PackageTags>html;reconciler;reconciliation;diff;diffing;keyholes</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!-- <PackageIcon>packageIcon.png</PackageIcon> -->
    <PackageProjectUrl>https://xtml.dev</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/web4foundation/web4-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Xtml.Templating/Xtml.Templating.csproj" />
    <EmbeddedResource Include="Assets/ui.js" />
    <EmbeddedResource Include="Assets/ui.css" />
    <EmbeddedResource Include="Assets/sw.js" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  
</Project>
